name: Go CD
env:
  AZURE_WEBAPP_NAME: go-app

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Go CI"]
  #   types:
  #     - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'Staging'
    steps:

      # - name: Pull Docker Image
      #   run: |
      #     docker login -u itsbharatsaini -p ${{ secrets.DOCKERHUB_TOKEN }}
      #     docker pull itsbharatsaini/go-app:latest

      - name: Deploy to VM
        run: |
          ssh user@staging-server 'docker stop go-app || true'
          ssh user@staging-server 'docker run -d -p 8080:8080 --name go-app itsbharatsaini/go-app:latest'

      # - name: Deploy to Azure Web App
      #   id: deploy-to-webapp
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      #     images: 'itsbharatsaini/go-app:latest'
